### ISSUE TITLE
Add Stylistic

### ISSUE THREAD

**Issue by KristjanESPERANTO** [GildedPleb/eslint-config-current-thing#2]
Since Stylistic (https://eslint.style/) originated directly from ESLint and is being actively developed, it would be a good addition. I am currently implementing it in my projects.

**Comment by KristjanESPERANTO** [comment]
@stylistic/eslint-plugin unifies 4 plugins and together they have 284 718 weekly downloads with a strong upward trend.

Weekly downloads:

[@stylistic/eslint-plugin](https://www.npmjs.com/package/@stylistic/eslint-plugin): 51 798
[@stylistic/eslint-plugin-js](https://www.npmjs.com/package/@stylistic/eslint-plugin-js): 87 983
[@stylistic/eslint-plugin-ts](https://www.npmjs.com/package/@stylistic/eslint-plugin-ts): 60 678
[@stylistic/eslint-plugin-jsx](https://www.npmjs.com/package/@stylistic/eslint-plugin-jsx): 51 985
[@stylistic/eslint-plugin-plus](https://www.npmjs.com/package/@stylistic/eslint-plugin-plus): 32 274

**Comment by GildedPleb** [comment]
Great find! I will indeed endeavor to incorporate this in a new release.
