### ISSUE TITLE
Add @eslint/js

### ISSUE THREAD

**Issue by KristjanESPERANTO** [GildedPleb/eslint-config-current-thing#3]
As @eslint/js are the rules from the official project, this would not only be a good addition but also a good basis. There are over 17 million weekly downloads.

https://www.npmjs.com/package/@eslint/js?activeTab=readme

**Comment by GildedPleb** [comment]
Indeed! It's in there! 

This week, I am doing an audit and refactor of the code base. A lot of projects have now (finally) moved to the new flat config format so I suspect there are some weird artifacts that might need to be cleaned up. Stay tuned for a new release. 


```
import eslint from "@eslint/js";
...
  /*
    ESLint
    47,535,610 monthly downloads
    ESLint JavaScript language implementation
    https://eslint.org
  */
  ...(disable.includes("@eslint/js")
    ? []
    : [
        {
          files,
          rules: {
            ...eslint.configs.recommended.rules,
            ...("@eslint/js" in override ? override["@eslint/js"] : {}),
          },
        },
      ]),
```
